<#
.SYNOPSIS
    Configures the deployed bot's Azure Active Directory v2 OAuth connection.
.DESCRIPTION
    Reuses the sign-in app, tenant and APIM scope from prerequisite 4.
    Validates the deployed agent/bot identity before any writes. Reuses matching
    public settings; -UpdateExisting is required for changes or secret rotation.
    Does not create an app registration, secret, bot, channel or Teams app.
#>
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
param(
    [string]$ConnectionName,
    [string]$ProjectEndpoint,
    [string]$AgentName,
    [string]$BotServiceArmId,
    [string]$EnvFile,
    [switch]$UpdateExisting
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '..\..\common-scripts\Common.ps1')
if (-not $EnvFile) { $EnvFile = Get-PrerequisiteEnvPath }
$values = Read-PrerequisiteEnv -Path $EnvFile
$ConnectionName = Resolve-PrerequisiteValue -Parameters $PSBoundParameters -ParameterName ConnectionName `
    -Values $values -Key AZURE_BOT_SERVICE_OAUTH_CONNECTION_NAME
if ($ConnectionName -cnotmatch '^[A-Za-z0-9][ A-Za-z0-9_.-]{1,63}$' -or $ConnectionName -cne $ConnectionName.Trim()) {
    throw 'Set AZURE_BOT_SERVICE_OAUTH_CONNECTION_NAME to a 2-64 character connection name using letters, digits, spaces, dots, underscores or hyphens.'
}
foreach ($key in @('AUTH_CLIENT_ID', 'AUTH_CLIENT_SECRET', 'AZURE_TENANT_ID', 'APIM_SCOPE')) {
    if ([string]::IsNullOrWhiteSpace($values[$key])) { throw "Set $key in '$EnvFile' before configuring bot OAuth." }
}
foreach ($key in @('AUTH_CLIENT_ID', 'AZURE_TENANT_ID')) {
    $guid = [Guid]::Empty
    if (-not [Guid]::TryParse($values[$key], [ref]$guid) -or $guid -eq [Guid]::Empty) {
        throw "$key must be a nonempty GUID."
    }
}
if ($values['APIM_SCOPE'] -cnotmatch '^api://[^\s]+/Mcp\.Invoke$') {
    throw 'APIM_SCOPE must be the api://.../Mcp.Invoke delegated scope generated by prerequisite 4.'
}
$context = Get-PublishingContext -Parameters $PSBoundParameters -EnvFile $EnvFile
$deploymentState = Get-PublishingState -Context $context
if ($deploymentState.Bot.properties.msaAppTenantId -ine $values['AZURE_TENANT_ID']) {
    throw 'AZURE_TENANT_ID does not match the deployed bot tenant. No OAuth settings were changed.'
}
$provider = Invoke-PublishingCli -Arguments @('bot', 'authsetting', 'list-providers', '--provider-name', 'Aadv2',
    '--subscription', $context.SubscriptionId) -Operation 'Read Azure Active Directory v2 OAuth provider'
$providerId = [Guid]::Empty
if ($provider.properties.serviceProviderName -ine 'Aadv2' -or
    -not [Guid]::TryParse([string]$provider.properties.id, [ref]$providerId) -or $providerId -eq [Guid]::Empty) {
    throw 'Azure returned an invalid Azure Active Directory v2 OAuth provider. No OAuth settings were changed.'
}
$resourceId = "$($context.BotServiceArmId)/connections/$ConnectionName"
$url = "https://management.azure.com$($context.BotServiceArmId)/connections/$([Uri]::EscapeDataString($ConnectionName))?api-version=2022-09-15"
$scopes = "openid profile offline_access $($values['APIM_SCOPE'])"
$expected = @{
    ResourceId = $resourceId
    ClientId = $values['AUTH_CLIENT_ID']
    TenantId = $values['AZURE_TENANT_ID']
    Scopes = $scopes
    ProviderId = [string]$providerId
}
$connections = @(Get-BotOAuthConnections -Context $context)
$existing = @($connections | Where-Object { $_.id -ieq $resourceId -or $_.name -ieq $ConnectionName })
if ($existing.Count -gt 1) { throw 'The bot returned multiple matching OAuth connections. Review the resource manually.' }
if ($existing.Count -eq 1 -and -not $UpdateExisting) {
    $existingConnection = Invoke-PublishingRequest -Context $context -Method GET -Url $url -Arm `
        -Operation 'Read existing bot OAuth connection'
    if (-not (Test-BotOAuthConnection -Connection $existingConnection @expected)) {
        throw "The named OAuth connection has conflicting public settings. Review them and rerun with -UpdateExisting; no writes were made."
    }
    Write-Host "OAuth connection '$ConnectionName' already matches. No Azure writes were needed. The saved secret cannot be verified; use -UpdateExisting to reapply or rotate it."
    return
}
if (-not $PSCmdlet.ShouldProcess($resourceId,
    'Create/update the Azure Active Directory v2 connection with the existing sign-in app secret, delegated scopes and an empty Token Exchange URL')) {
    Write-Host 'No OAuth settings were changed.'
    return
}
if (-not $UpdateExisting) {
    $current = @(Get-BotOAuthConnections -Context $context | Where-Object {
        $_.id -ieq $resourceId -or $_.name -ieq $ConnectionName
    })
    if ($current.Count) {
        throw 'The named OAuth connection appeared after confirmation. Rerun to review/reuse it; no write was made.'
    }
}
$body = @{
    location = $deploymentState.Bot.location
    properties = @{
        clientId = $values['AUTH_CLIENT_ID']
        clientSecret = $values['AUTH_CLIENT_SECRET']
        serviceProviderId = [string]$providerId
        scopes = $scopes
        parameters = @(
            @{ key = 'TenantId'; value = $values['AZURE_TENANT_ID'] }
            @{ key = 'TokenExchangeUrl'; value = '' }
        )
    }
}
Invoke-PublishingRequest -Context $context -Method PUT -Url $url -Arm -Body $body `
    -Operation 'Configure bot OAuth connection' -NoContent
for ($attempt = 0; $attempt -lt 6; $attempt++) {
    $verified = Invoke-PublishingRequest -Context $context -Method GET -Url $url -Arm -Operation 'Verify bot OAuth connection'
    if (Test-BotOAuthConnection -Connection $verified @expected) {
        Write-Host "Verified OAuth connection '$ConnectionName': Azure Active Directory v2, configured tenant and delegated APIM scope, empty Token Exchange URL. Secret read-back and interactive user sign-in are not verified. Run post-requisite 2 next."
        return
    }
    if ($attempt -lt 5) { Start-Sleep -Seconds 2 }
}
throw 'The OAuth connection write completed, but its public settings could not be verified. Completed writes remain; inspect the connection and rerun. No success was reported.'
