openapi: 3.0.1
info:
  title: Atlassian Connect
  description: ''
  version: '1.0'
servers:
  - url: https://flopes-swc-demo-apim.azure-api.net/atlassian-connect
paths:
  /status:
    get:
      summary: Get status
      operationId: get-status
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]